In [1]:
################矩阵操作
y <- matrix(1:20, nrow=5, ncol=4)
y
y <- matrix(1:20,nrow=5, ncol=4,byrow = T)
y

y <- matrix(1:20,nrow=5, byrow = T)
y

cells <- c(1,24,26,68)
mymatrix <- matrix(cells, nrow=2, ncol=2, byrow=TRUE)
mymatrix

x <- matrix(1:10, nrow=2)
x
x[2,]
x[,2]
x[1,4]
x[1, c(4,5)]
mydata<-data.frame("序号"=c("g001","g002","g003"),"性别"=c("男","男","女"),"年龄"=c(20,19,19))
mydata
genotype <- read.table("./Y.txt",header = F)
# genotype[1:100]
write.table(genotype,'da.txt',sep = ";")
# 创建一个示例数据框
df <- data.frame(Name = c("Alice", "Bob", "Charlie"),
                 Age = c(25, 30, 35),
                 Height = c(165, 170, 180))
df$Age
df[,c(1,3)]
df[1,]
df[,1]
df[1:3,]
df[,1:2]
df2 <- data.frame(Height = c(165, 170, 180),
                  HairColor = c("Black", "Brown", "Blonde"),
                  Age = c(25, 30, 35))
grep("^H",names(df2))
df2
names(df2)
colnames(df2)
names(df2) <- c('Q1','Q2','Q3')
rownames(df2) <- c("Person1", "Person2", "Person3")
df2
# 合并
df1 <- data.frame(Name = "Alice", Age = 25)
df2 <- data.frame(Name = "Bob", Age = 30)
df1
df2
df3 <- cbind(df1,df2)
df3
df4 <- rbind(df1,df2)
df4
df1 <- data.frame(ID = c(1, 2, 3),
                  Name = c("Alice", "Bob", "Charlie"))

df2 <- data.frame(ID = c(2, 3, 4),
                  Age = c(30, 35, 40))
df1
df2
# 按 ID 列进行连接
merged_df <- merge(df1, df2, by = "ID")
merged_df
# Creating list
g <- "My First List"
h <- c(25, 26, 18, 39)
j <- matrix(1:10, nrow=5)
k <- c("one", "two", "three")
mylist <- list(title=g, ages=h, sun=j, k)
mylist

mylist[[2]]
mylist[2]
mylist[["ages"]]
mylist$ages
mylist[[3]]
mylist[[3]][1,2]
# 数据集排序
# Creating a graph
plot(mtcars$wt,mtcars$mpg)
abline(lm(mtcars$mpg~mtcars$wt))
title("Regression of MPG on Weight")

# Creating and saving a graph
# (1) Using "save as" option in the plotting window of R or Rstudio
# (2) Directly print the graph in a file 
tiff("mygraph.tif", width = 18, height = 12, units = 'cm', res = 300)
plot(mtcars$wt,mtcars$mpg)
abline(lm(mtcars$mpg~mtcars$wt))
title("Regression of MPG on Weight")
dev.off()

[,1] [,2] [,3] [,4]
[1,] 1     6   11   16  
[2,] 2     7   12   17  
[3,] 3     8   13   18  
[4,] 4     9   14   19  
[5,] 5    10   15   20

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16  
[5,] 17   18   19   20

[,1] [,2]
[1,]  1   24  
[2,] 26   68

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[1]  2  4  6  8 10

[1] 3 4

[1] 7

[1] 7 9

序号 性别 年龄
1 g001 男   20  
2 g002 男   19  
3 g003 女   19

Warning message in file(file, "rt"):
"cannot open file './Y.txt': No such file or directory"


ERROR: Error in file(file, "rt"): cannot open the connection
