In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import chisquare,chi2_contingency

plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

In [2]:
# 拟合优度检验
# a:b
flower = pd.read_csv('flower.csv')
f_obs = flower['num']
f_exp = f_obs.sum()*flower['exp']
chi2,p_value = chisquare(f_obs=f_obs,f_exp=f_exp)
print(f'自由度：{len(f_obs)-1}，F统计量：{chi2:.4f}，p值：{p_value:.4f}')
# a:b:c
f_obs = pd.Series([335,125,160])
exp = pd.Series([9/16,3/16,4/16])
f_exp = f_obs.sum()*exp
chi2,p_value = chisquare(f_obs=f_obs,f_exp=f_exp)
print(f'自由度：{len(f_obs)-1}，F统计量：{chi2:.4f}，p值：{p_value:.4f}')
# a:b:c:d
f_obs = pd.Series([491,76,90,86])
exp = pd.Series([9/16,3/16,3/16,1/16])
f_exp = f_obs.sum()*exp
chi2,p_value = chisquare(f_obs=f_obs,f_exp=f_exp)
print(f'自由度：{len(f_obs)-1}，F统计量：{chi2:.4f}，p值：{p_value:.4f}')

自由度：1，F统计量：0.9013，p值：0.3424
自由度：2，F统计量：1.3620，p值：0.5061
自由度：3，F统计量：92.7063，p值：0.0000


In [3]:
# 适合性检验 
# 2x2
x = [[26,184],[50,200]]
df = pd.DataFrame(x,index=['发病株数','未发病株数'],columns=['拌种','未拌种'])
chi2,p_value,df,f_exp = chi2_contingency(df,correction=False) # 默认Yates连续性校正
print(f'自由度：{df}，F统计量：{chi2:.4f}，p值：{p_value:.4f}')
print(np.round(f_exp,4))

自由度：1，F统计量：4.8037，p值：0.0284
[[ 34.6957 175.3043]
 [ 41.3043 208.6957]]


In [4]:
# rxc
x = [[12,224,76],
     [60,548,39],
     [246,659,28],
     [416,765,47]]
df = pd.DataFrame(x,index=['A','B','C','D'],columns=['一穗枝蔓数','二穗枝蔓数','三穗枝蔓数'])
chi2,p_value,df,f_exp = chi2_contingency(df,correction=False) # 默认Yates连续性校正
print(f'自由度：{df}，F统计量：{chi2:.4f}，p值：{p_value:.4f}')
print(np.round(f_exp,4))

自由度：6，F统计量：392.6328，p值：0.0000
[[ 73.4    219.6     19.    ]
 [152.2109 455.3885  39.4006]
 [219.4942 656.6885  56.8173]
 [288.8949 864.3231  74.7821]]
