In [1]:
import numpy as np

## 选择排序
#### 找大（小）放前

In [40]:
# 案例
# def selection_sort(x):
#     for i in range(len(x)):
#         swap = i + np.argmin(x[i:])
#         x[i], x[swap] = x[swap], x[i]
#     return x
# x = [2, 1, 4, 3, 5]
# print(selection_sort(x))
x = [4, 5, 2, 3, 1]
def se_sort(x):
    for i in range(len(x)):
        a = i + np.argmax(x[i:])
        # print(a)
        # print(x[i:]) 因为列表未变，交换的是原列表而非x[i:]列表
        x[a], x[i] = x[i], x[a]
        # print(x[i:])
    return x
se_sort(x)

[5, 4, 3, 2, 1]

## bogosort排序
#### 打乱再看是否排好，寻天意

In [ ]:
def bogosort(x):
    while np.any(x[:-1]>x[1:]):
        np.random.shuffle(x)
    return x
x = np.array([7, 9, 2, 6, 4, 3])
print(bogosort(x))

## 快速排序
#### np.sort()/np.argsort()

In [43]:
x = np.array([7,9,2,6,4,3])
# 不修改原始数组的基础上，返回一个排好序的数组
print(np.sort(x))
print(x)
# 希望用排好序的数组替代原数组
x.sort()
print(x)
# 返回排好序的索引值
z = np.array([9, 8, 5, 3, 7, 6, 1, 0])
i = np.argsort(z)
print(i)
print(z[i])

[2 3 4 6 7 9]
[7 9 2 6 4 3]
[2 3 4 6 7 9]
[7 6 3 2 5 4 1 0]
[0 1 3 5 6 7 8 9]


## 行列排序
#### 

In [45]:
rand = np.random.RandomState(42)
x = rand.randint(0,10,(4,6))
print(x)
# 列
print(np.sort(x,axis=0))
# 行
print(np.sort(x,axis=1))

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


## 部分排序
#### 不对整个数组排序，找到第K个小的值
#### 输出一个新的数组，最左边是第K小的值

In [48]:
x = np.array([7,6,5,2,3,1,4])
print(np.partition(x, 3))
# 返回第K个小的值的索引
print(np.argpartition(x, 3))
# 沿轴第K个小的值
x = rand.randint(0, 10, (4, 6))
print(np.partition(x, 3, axis=0))  # 行里最小的三行
print(np.partition(x, 3, axis=1))  # 列里最小的三列

[3 2 1 4 6 5 7]
[4 3 5 6 1 2 0]
[[3 5 1 0 1 1]
 [3 3 1 5 3 4]
 [6 7 2 8 5 9]
 [7 7 6 9 7 9]]
[[0 1 2 3 6 7]
 [3 1 5 5 7 9]
 [1 1 3 5 9 9]
 [3 4 6 7 7 8]]
