In [1]:
# 生成结构化数组
import numpy as np
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [11]:
# 字典
# np.dtype以字典形式定义数组中各数据的类型
i = np.dtype({'names': ('name', 'age', 'weight'),
              'formats': ('U10', 'i4', 'f8')})
data = np.zeros(4, i)
print(data)
# 赋予类型字典中各内容
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [4]:
# 元组
# np.dtype以元组形式定义数组中各数据的类型
i = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])
data = np.zeros(4, i)
print(data)
# 赋予类型元组中各内容
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [8]:
# 直接指定
i = np.dtype('U10,i4,f8')
data = np.zeros(4, i)
print(data)

[('', 0, 0.) ('', 0, 0.) ('', 0, 0.) ('', 0, 0.)]


In [9]:
i = np.dtype({'names': ('name', 'age', 'weight'), 
              'formats': ('U10', 'i4', 'f8')})
data = np.zeros(4, i)
data['name'] = name
data['age'] = age
data['weight'] = weight
# 获取值
print(data['name'])
# 获取首行
print(data[0])
# 获取最后一行名字
print(data[-1]['name'])
# 筛选
print(data[data['age'] < 28]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
('Alice', 25, 55.)
Doug
['Alice' 'Doug']


In [12]:
# 更复杂的数据类型
# 包含一个元组，含有数组和3x3矩阵
i = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
x = np.zeros(1, i)
print(x)
print(x[0])
print(x[-1])
print(x['mat'])
print(x['id'])

[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[0]


In [18]:
# np.recarray类，像字典一样获取值,
# 记录一个数组，并用简单的语法输出
i = np.dtype({'names': ('name', 'age', 'weight'),
              'formats': ('U10', 'i4', 'f8')})
data = np.zeros(4, i)
data['name'] = name
data['age'] = age
data['weight'] = weight
data_rec = data.view(np.recarray)
print(data_rec.age)

[25 45 37 19]


In [19]:
# 不论是data['age']、data_rec['age']、data_rec.age
# data['age']更快一些