In [1]:
import numpy as np
# 生成伪随机数 ==> 与其他隔离的生成器
# 只想在某个变量用伪随机就用randomstate
i = np.random.RandomState(1)
print(i)

RandomState(MT19937)


In [2]:
# 生成固定随机数 ==> 全局的伪随机生成器
i = np.random.seed(1)
print(i)

None


In [14]:
# 随机整数
# i = np.random.seed(1)
# np.random.RandomState(1)
print(np.random.randint(0, 10, (2, 3)))

[[8 7 3]
 [6 5 1]]


In [15]:
# 随机浮点数
print(np.random.uniform(1, 10, (2, 3)))

[[5.79848756 7.22689403 3.83964068]
 [7.17850835 8.51163105 1.1645945 ]]


In [16]:
# 符合正态分布样本值
print(np.random.rand(100))

[0.75014431 0.98886109 0.74816565 0.28044399 0.78927933 0.10322601
 0.44789353 0.9085955  0.29361415 0.28777534 0.13002857 0.01936696
 0.67883553 0.21162812 0.26554666 0.49157316 0.05336255 0.57411761
 0.14672857 0.58930554 0.69975836 0.10233443 0.41405599 0.69440016
 0.41417927 0.04995346 0.53589641 0.66379465 0.51488911 0.94459476
 0.58655504 0.90340192 0.1374747  0.13927635 0.80739129 0.39767684
 0.1653542  0.92750858 0.34776586 0.7508121  0.72599799 0.88330609
 0.62367221 0.75094243 0.34889834 0.26992789 0.89588622 0.42809119
 0.96484005 0.6634415  0.62169572 0.11474597 0.94948926 0.44991213
 0.57838961 0.4081368  0.23702698 0.90337952 0.57367949 0.00287033
 0.61714491 0.3266449  0.5270581  0.8859421  0.35726976 0.90853515
 0.62336012 0.01582124 0.92943723 0.69089692 0.99732285 0.17234051
 0.13713575 0.93259546 0.69681816 0.06600017 0.75546305 0.75387619
 0.92302454 0.71152476 0.12427096 0.01988013 0.02621099 0.02830649
 0.24621107 0.86002795 0.53883106 0.55282198 0.84203089 0.1241