In [ ]:
import numpy as np
# 标准三角函数  3\4\5
# 正弦函数 sin(x)
print(np.sin(4/5))
# 余弦函数 cos(x)
print(np.cos(4/5))
# 正切函数 tan(x)
print(np.tan(4/5))
# 反正弦函数
print(np.arcsin(4/5))
# 反余弦函数
print(np.arccos(4/5))
# 反正切函数
print(np.arctan(4/5))

0.7173560908995228


In [2]:
# 四舍五入
x = [1.22,2.33,6.789,5.634]
print(np.around(x,1))

[1.2 2.3 6.8 5.6]


In [3]:
# 对元素向下取整
x = [-0.2,-1.5,0.5,1.6]
print(np.floor(x))

[-1. -2.  0.  1.]


In [4]:
# 对元素向上取整
x = [-0.2,-1.5,0.5,1.6]
print(np.ceil(x))

[-0. -1.  1.  2.]
