In [1]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(5, size=(2, 3))
x3 = np.random.randint(5, size=(2, 3, 4))

In [3]:
# 维度
print(x1.ndim, x2.ndim, x3.ndim)

1 2 3


In [3]:
# 每组每个维度的大小
print(x1)
print(x2)
print(x3)
print(x1.shape,x2.shape,x3.shape)
#TODO 
# 先画一个3*4的数组，在用2个包起来，就是（2，3，4）

[5 0 3 3 7 9]
[[3 2 4]
 [0 0 4]]
[[[2 1 0 1]
  [1 0 1 4]
  [3 0 3 0]]

 [[2 3 0 1]
  [3 3 3 0]
  [1 1 1 0]]]
(6,) (2, 3) (2, 3, 4)


In [4]:
# 数组的总大小 ——> 每组每个维度大小的累乘
print(x1.size, x2.size, x3.size)

6 6 24


In [5]:
# 数组的类型
print(x1.dtype, x2.dtype, x3.dtype)

int32 int32 int32


In [6]:
# 每个数组元素字节大小 ——> 整数为4，浮点数为8
print(x1.itemsize, x2.itemsize, x3.itemsize)

4 4 4


In [7]:
# 数组的总字节大小 ——> 数组的总大小与每个数组元素字节大小相乘
print(x1.nbytes, x2.nbytes, x3.nbytes)

24 24 96
