In [2]:
import numpy as np
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(5, size=(2, 3))
x3 = np.random.randint(5, size=(2, 3, 4))

In [3]:
# TODO: 数组的索引
# 等同与列表
## 获取值
print(x1[0],x2[1][1],x3[-1][-2])
print(x1[0],x2[1,1],x3[-1,-2])
## 修改值
x2[1,1] = 5
print(x2[1,1])
## 自动截断
x2[1,1] = 5.533333
print(x2[1,1])
print(x2)

5 0 [3 3 3 0]
5 0 [3 3 3 0]
5
5
[[3 2 4]
 [0 5 4]]


In [4]:
# TODO: 数组的切片
# 等同与列表
# 一维
print(x1)
print(x1[:3])
print(x1[1:4:2])

[5 0 3 3 7 9]
[5 0 3]
[0 3]


In [8]:
# 多维
# print(x2)
print(x3)
# print(x2[:1,:2])
# 各元素指代 [个，行，列]
print(x3[:1, :2, :3])
print(x3[::-1, ::-1, ::-1])

[[[2 1 0 1]
  [1 0 1 4]
  [3 0 3 0]]

 [[2 3 0 1]
  [3 3 3 0]
  [1 1 1 0]]]
[[[2 1 0]
  [1 0 1]]]
[[[0 1 1 1]
  [0 3 3 3]
  [1 0 3 2]]

 [[0 3 0 3]
  [4 1 0 1]
  [1 0 1 2]]]


In [9]:
# 取出某一列，某一行 [行，列]
print(x2)
print(x2[:, 0])  # 第一列
print(x2[0, :])  # 第一行

[[3 2 4]
 [0 5 4]]
[3 0]
[3 2 4]


In [4]:
# 视图与副本
x2[0][0] = 99
print(x2)   # 此时返回的是一个[视图]
y = x2.copy()   # 创建的是一个[副本]
print(y)
y[1][1] = 111
print(y)
print(x2)

[[99  2  4]
 [ 0  0  4]]
[[99  2  4]
 [ 0  0  4]]
[[ 99   2   4]
 [  0 111   4]]
[[99  2  4]
 [ 0  0  4]]
