In [1]:
import numpy as np
# 数组的变形——>reshape()
grid = np.arange(1, 10)
print(grid.reshape((3, 3)))
# 行向量
print(grid.reshape((1, 9)))
print(grid[np.newaxis, :])
# 列向量
print(grid.reshape((9, 1)))
print(grid[:, np.newaxis])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [4]:
# 数组的拼接

In [6]:
# 一维直接拼接np.concatenate
x = np.arange(1, 5)
y = np.arange(6, 10)
z = [99, 99]
print(np.concatenate([x, y]))
print(np.concatenate([x, y, z]))

[1 2 3 4 6 7 8 9]
[ 1  2  3  4  6  7  8  9 99 99]


In [3]:
# 二维数组拼接，[默认行/垂直栈]
x = [[1, 2, 3], [4, 5, 6]]
print(np.concatenate([x, x]))
# axis = 0 ==> np.vstack()
print(np.concatenate([x, x], axis=0))  # 行/垂直栈
print(np.vstack([x, x]).shape)
# axis = 1 ==> np.hstack()
print(np.concatenate([x, x], axis=1))  # 列/水平栈
print(np.hstack([x, x]).shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
(4, 3)
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
(2, 6)


In [11]:
# 数组的分裂
x = np.arange(16)
grid = np.arange(16).reshape((4, 4))
print(x)
print(grid)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [12]:
# 索引分割,索引为下一个的开头
x1, x2, x3 = np.split(x, [5, 9])
x4, x5, x6 = np.split(grid, [1, 3])
print(x1, x2, x3)
print(x4, x5, x6)

[0 1 2 3 4] [5 6 7 8] [ 9 10 11 12 13 14 15]
[[0 1 2 3]] [[ 4  5  6  7]
 [ 8  9 10 11]] [[12 13 14 15]]


In [13]:
# vsplit() ==> axis=0   垂直栈
up, lo = np.vsplit(grid, [2])
up1, lo1 = np.split(grid, [2], axis=0)
print(up, lo)
print(up1, lo1)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [14]:
# hsplit() ==> axis=1   水平栈
up, lo = np.hsplit(grid, [2])
up1, lo1 = np.split(grid, [2], axis=1)
print(up, lo)
print(up1, lo1)
# dsplit() ==> axis=2

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
