In [1]:
# 使用python自带的函数进行操作太缓慢，故而引入numpy的通用函数，调用C语言进行操作，反而更快
import numpy as np
x = np.arange(5)
print(x)
# 基本运算
# + 加
print(x+10)
print(np.add(x, 10))
# - 减
print(x-10)
print(np.subtract(x, 10))
# - 负数
print(-x)
print(np.negative(x))
# * 乘
print(x*10)
print(np.multiply(x ,10))
# / 除
print(x/10)
print(np.divide(x, 10))
# // 整除
print(x//2)
print(np.floor_divide(x, 2))
# ** 幂
print(x**2)
print(np.power(x, 2))
# % 取余
print(x % 3)
print(np.mod(x, 3))

[0 1 2 3 4]
[10 11 12 13 14]
[10 11 12 13 14]
[-10  -9  -8  -7  -6]
[-10  -9  -8  -7  -6]
[ 0 -1 -2 -3 -4]
[ 0 -1 -2 -3 -4]
[ 0 10 20 30 40]
[ 0 10 20 30 40]
[0.  0.1 0.2 0.3 0.4]
[0.  0.1 0.2 0.3 0.4]
[0 0 1 1 2]
[0 0 1 1 2]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
[0 1 2 0 1]
[0 1 2 0 1]


In [2]:
# 绝对值
# |x|
y = np.array([-1, -2, -3, 3, 5, 6])
print(np.abs(y))

[1 2 3 3 5 6]


In [3]:
# 三角函数
z = np.linspace(0, np.pi, 9)
r = [-1, 0, 1]
print(z)
# y = sin(x)
print(np.sin(z))
# y = arcsin(x) ==> 反函数
print(np.arcsin(r))
# y = cos(x)
print(np.cos(z))
# y = arccos(x) ==> 反函数
print(np.arccos(r))
# y = tan(x)
print(np.tan(z))
# y = arctan(x) ==> 反函数
print(np.arctan(r))

[0.         0.39269908 0.78539816 1.17809725 1.57079633 1.96349541
 2.35619449 2.74889357 3.14159265]
[0.00000000e+00 3.82683432e-01 7.07106781e-01 9.23879533e-01
 1.00000000e+00 9.23879533e-01 7.07106781e-01 3.82683432e-01
 1.22464680e-16]
[-1.57079633  0.          1.57079633]
[ 1.00000000e+00  9.23879533e-01  7.07106781e-01  3.82683432e-01
  6.12323400e-17 -3.82683432e-01 -7.07106781e-01 -9.23879533e-01
 -1.00000000e+00]
[3.14159265 1.57079633 0.        ]
[ 0.00000000e+00  4.14213562e-01  1.00000000e+00  2.41421356e+00
  1.63312394e+16 -2.41421356e+00 -1.00000000e+00 -4.14213562e-01
 -1.22464680e-16]
[-0.78539816  0.          0.78539816]


In [4]:
# 指数和对数
from math import log1p

x = [1, 2, 3]
print(x)
# e^x
print(np.exp(x))
# 2^x
print(np.exp2(x))
# 3^x
print(np.power(3,x))
# ln(x)
print(np.log(x))
# log2(x)
print(np.log2(x))
# log10(x)
print(np.log10(x))
# e^x + 1
print(np.expm1(x))
# ln(1 + x)
print(np.log1p(x))

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[ 3  9 27]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]
[0.         0.30103    0.47712125]
[ 1.71828183  6.3890561  19.08553692]
[0.69314718 1.09861229 1.38629436]


In [5]:
# 函数特性
# TODO y输出可以指定存储到y1中去
y1 = np.zeros(10)
y = np.arange(10)
print(np.add(y, 9, out=y1[::-1]))

[ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [7]:
# TODO 聚合
# 一维
x = np.arange(1, 11)
print(x)
# add通用函数的reduce方法 ==> 累加
print(np.add.reduce(x))
print(np.add.accumulate(x))  # 存储每次计算的结果
# multiply通用函数的reduce方法 ==> 累积
print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))    # 存储每次计算的结果

[ 1  2  3  4  5  6  7  8  9 10]
55
[ 1  3  6 10 15 21 28 36 45 55]
3628800
[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [2]:
# 二维
# 1是横轴，从左到右；0是纵轴，从上到下
x = np.arange(1, 11).reshape((5, 2))
print(x.sum())
print(x.min())
print(x.max())
print(x)
# ...
# min(),max()...类似于以下sum()
# axis=0 垂直栈
print(x.sum(axis=0))
# axis=1 水平栈
print(x.sum(axis=1))

55
1
10
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[25 30]
[ 3  7 11 15 19]


In [3]:
# TODO 外积
r = np.arange(1,10)
print(r)
# add通用函数的outer方法 ==> 广播累加
print(np.add.outer(r, r))
# multply通用函数的outer方法 ==> 广播累积
print(np.multiply.outer(r, r))

[1 2 3 4 5 6 7 8 9]
[[ 2  3  4  5  6  7  8  9 10]
 [ 3  4  5  6  7  8  9 10 11]
 [ 4  5  6  7  8  9 10 11 12]
 [ 5  6  7  8  9 10 11 12 13]
 [ 6  7  8  9 10 11 12 13 14]
 [ 7  8  9 10 11 12 13 14 15]
 [ 8  9 10 11 12 13 14 15 16]
 [ 9 10 11 12 13 14 15 16 17]
 [10 11 12 13 14 15 16 17 18]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [7]:
# numpy统计函数
# python通用的是sum(),min(),max()...不做讲解
# python Numpy通用函数
# 如果数据中存在NaN,应当在函数前面加nan
# nansum(),nanmin(),...
# 求和
L = np.arange(1, 101)
print(L)
# print(np.sum(L))
# # 最小值、最大值及其索引
# print(np.min(L))
# print(np.argmin(L))
# print(np.max(L))
# print(np.argmax(L))
# 求积
print(np.prod(L))   # 与np.multiply.reduce()类似超过33后为0、超出限制、不符合规范
# 平均值 ==> (x1+x2+x3+...+xn)/n
print(np.mean(L))
# 标准差 ==> (((x1-u)^2+...+(xn-u)^2)/n)^0.5
print(np.std(L))
print(np.nanstd(L))
# 方差 ==> 标准差的平方
print(np.var(L))
# 中位数
print(np.median(L))
# 基于元素排序的统计值 ==> (P/(100/(N-1)))+1 ==> 未知？
print(np.percentile(L, 75))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
0
50.5
28.86607004772212
28.86607004772212
833.25
50.5
75.25


In [8]:
A = [0, 1, 0, 1, 0]
# 判断任意元素是否为真 ==> or关系
print(np.any(A))
# 判断所有元素是否为真 ==> and关系
print(np.all(A))

True
False
