In [2]:
# 用于不同大小数组的二进制通用函数的一组规则
import numpy as np
a = np.array([0, 1, 2])
b = np.ones((3, 3))
c = np.ones((4, 4))
print(a+a)
print(a+5)
print(a+b)
# print(a+c)   # 报错 形状不同似乎不能广播

[0 2 4]
[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [3]:
# 规则1：如果两个数组的维度数不同，那么小维度数组的形状将会在最左边补1.
a = np.ones((2, 3))
print(a)
b = np.arange(3)
print(b)
print(a.shape)
print(b.shape)
print(a+b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
(2, 3)
(3,)
[[1. 2. 3.]
 [1. 2. 3.]]


In [4]:
# 规则2：如果两个数组的形状在任何一个维度上都不匹配，那么数组的形状会沿着维度为1的维度扩展以匹配
# 另外一个数组的形状
a = np.ones((3, 1))
print(a)
b = np.arange(3)
print(b)
print(a.shape, b.shape)
# 按规则1在最左边补充1，按规则2在数组维度是1的方向扩展来匹配
print(a+b)

[[1.]
 [1.]
 [1.]]
[0 1 2]
(3, 1) (3,)
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [5]:
# 规则3：如果两个数组的形状在任何一个维度上都不匹配并且没有一个维度上等于1，那么会引发异常.
a = np.ones((3, 2))
print(a)
b = np.arange(3)
print(b)
print(a.shape, b.shape)
# 按规则1在最左边补充1，按规则2在数组维度是1的方向扩展来匹配
# 但是维度依旧不匹配，故无法进行广播
# 但可以将b转换为列进行广播计算
print(a+b[:, np.newaxis])

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]
(3, 2) (3,)
[[1. 1.]
 [2. 2.]
 [3. 3.]]


In [10]:
# logaddexp(a,b) ==> log(exp(a)+exp(b)) 但是比log(exp(a)+exp(b))更准确
a = np.ones((3, 1))
print(a)
b = np.arange(3)
print(b)
print(np.logaddexp(a, b))

[[1.]
 [1.]
 [1.]]
[0 1 2]
[[1.31326169 1.69314718 2.31326169]
 [1.31326169 1.69314718 2.31326169]
 [1.31326169 1.69314718 2.31326169]]


In [8]:
# 广播的实际应用
# 数组的归一化
x = np.random.random((10, 3))
print(x)
# 求取均值
print(x.mean(0))  # 垂直栈
print(x.mean(0)-x)
print(x.mean(1))  # 水平栈
# print(x.mean(1)-x)
# 画一个二维函数
# ??????

[[0.98030107 0.91341988 0.22523088]
 [0.99339108 0.72414485 0.0390724 ]
 [0.4367549  0.68671049 0.9555612 ]
 [0.46315865 0.1480107  0.30160051]
 [0.47573843 0.62390089 0.10503071]
 [0.98947512 0.18383892 0.13939452]
 [0.07316473 0.12474442 0.18952378]
 [0.03658304 0.29973292 0.98240706]
 [0.08004405 0.31003743 0.0394934 ]
 [0.73461849 0.40275047 0.02603673]]
[0.52632296 0.4417291  0.30033512]
[[-0.45397812 -0.47169079  0.07510424]
 [-0.46706812 -0.28241575  0.26126272]
 [ 0.08956805 -0.24498139 -0.65522609]
 [ 0.06316431  0.2937184  -0.00126539]
 [ 0.05058452 -0.1821718   0.19530441]
 [-0.46315216  0.25789018  0.1609406 ]
 [ 0.45315823  0.31698467  0.11081134]
 [ 0.48973992  0.14199618 -0.68207194]
 [ 0.4462789   0.13169167  0.26084172]
 [-0.20829554  0.03897863  0.27429838]]
[0.70631728 0.58553611 0.69300887 0.30425662 0.40155668 0.43756952
 0.12914431 0.43957434 0.14319163 0.3878019 ]
