In [1]:
# 比较
import numpy as np
# 一维
x = np.array([1,2,3,4,5,6,7,8,9,10])
# 大于
print(x > 5)
print(np.greater(x, 5))
# 小于
print(x < 5)
print(np.less(x, 5))
# 大于等于
print(x >= 5)
print(np.greater_equal(x, 5))
# 小于等于
print(x <= 5)
print(np.less_equal(x, 5))
# 不等于
print(x != 5)
print(np.not_equal(x, 5))
# 等于
print(x == 5)
print(np.equal(x, 5))
# 二维
y = np.empty((3, 3))
print(np.less(y, 0))

[False False False False False  True  True  True  True  True]
[False False False False False  True  True  True  True  True]
[ True  True  True  True False False False False False False]
[ True  True  True  True False False False False False False]
[False False False False  True  True  True  True  True  True]
[False False False False  True  True  True  True  True  True]
[ True  True  True  True  True False False False False False]
[ True  True  True  True  True False False False False False]
[ True  True  True  True False  True  True  True  True  True]
[ True  True  True  True False  True  True  True  True  True]
[False False False False  True False False False False False]
[False False False False  True False False False False False]
[[False False False]
 [False False False]
 [False False False]]


In [2]:
# 操作布尔数组
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 统计True的个数
print(np.count_nonzero(a < 5), np.count_nonzero(b < 5))
print(np.sum(a < 5), np.sum(b < 5))
# 此时Flase = 0,True=1,此时的sum计算的是True与Flase
print(np.sum(b < 5, axis=1))

4 4
4 4
[3 1 0]


In [3]:
# 判断
# any ==> or all ==> and
print(np.any(a < 5), np.all(a < 5))
print(np.any(a < 5, axis=0), np.all(a < 5, axis=0))
# python内置sum\any\all不可以与numpy混用，否则会发生不可预估的错误
# 布尔运算符
# & ==> and
print(np.sum((b < 7) & (b > 5)))
print(np.sum(np.bitwise_and((b < 7), (b > 5))))
# | ==> or
print(np.sum((b < 7) | (b > 5)))
print(np.sum(np.bitwise_or((b < 7), (b > 5))))
# ^ ==> 异或
print(np.sum((b < 7) ^ (b > 5)))
print(np.sum(np.bitwise_xor((b < 7), (b > 5))))
# ~ ==> 反
print(np.sum(~((b < 7) ^ (b > 5))))
print(np.sum(np.bitwise_not(np.bitwise_xor((b < 7), (b > 5)))))

True False
True False
1
1
9
9
8
8
1
1


In [5]:
# 布尔数组作为掩码
x = np.array([[2,0,3,3],[7,9,3,5],[2,4,7,6]])
print(x)
# 为x创建一个掩码
b = x < 5
# 获取值
print(b)
print(x[b])

[[2 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[ True  True  True  True]
 [False False  True False]
 [ True  True False False]]
[2 0 3 3 3 2 4]


In [7]:
# and or 和 & | 的区别
# and or 判断整个对象的真或假
# & | 判断每个对象的比特位
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(np.sum((b < 7) & (b > 5)))
# print(np.sum((b<7) and (b>5))) # 报错，无法比较
print(np.sum((b < 7) | (b > 5)))
# print(np.sum((b<7) or (b>5))) # 报错，无法比较

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
