In [1]:
import numpy as np
# 一维
x = np.random.randint(111, size=11)
print(x)

[108  27  86  10  26  16  29  23  65  40  74]


In [2]:
# 通过三种方式获取值
# 🕛
print([x[2],x[7],x[9],x[10]])
# 🕑
ind = [2,7,9,10]
print(x[ind])
# 🕒
ind = np.array([[2,7],[9,10]])
print(x[ind])

[86, 23, 40, 74]
[86 23 40 74]
[[86 23]
 [40 74]]


In [3]:
# 多维
# 第一个是行，第二个是列,起始为0
# 索引配对遵循广播的规则
y = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(y[2,3])
print(y)
row = [0,1,2]
col = [2,1,3]
print(y[row,col])

11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  5 11]


In [4]:
# 组合索引
# 简单+花哨
print(y[2,[2,1,3]])
# 索引+切片
print(y[1:,[2,1,3]])
# 广播+索引+掩码
mask = np.array([1,0,1,0],dtype=bool)
row = np.array([[0],[1],[2]])
print(y[row,mask])

[10  9 11]
[[ 6  5  7]
 [10  9 11]]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [5]:
# 索引的修改
x = np.arange(10)
i = np.array([2,1,8,4])
x[i] = 99
print(x)
x[i] -= 10
print(x)

[ 0 99 99  3 99  5  6  7 99  9]
[ 0 89 89  3 89  5  6  7 89  9]


In [7]:
# 累加
x = np.zeros(10)
i = [2,3,3,4,4,4]
x[i] += 1
# x[i] += 1 ==> x[i] = x[i] + 1 并不是相加而是简单的赋值,故不变
print(x)
# np.add.at 对给定的操作 给定的索引 给定的值 执行就地操作.
np.add.at(x,i,1)
print(x)

[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
[0. 0. 2. 3. 4. 0. 0. 0. 0. 0.]
