In [2]:
import numpy as np

In [5]:
a = np.arange(12)
b = a.reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# 二维数组转换为向量
c = b.flatten()
print(c)
c[0] = 99
print(c)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[99  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
