In [2]:
import numpy as np

a = np.array([[4,3,1],[1,-2,3],[5,7,0]])
b = np.array([[7],[2],[1]])
print(np.dot(a,b))

[[35]
 [ 6]
 [49]]


# np.dot()相当于计算矩阵的乘法

In [9]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b))

130


# np.vdot()计算向量的内积

In [10]:
a = [[1,0],[0,1]] 
b = [[4,1],[2,2]] 
print (np.matmul(a,b))

[[4 1]
 [2 2]]


# np.matmul()计算矩阵乘积

In [13]:
a = np.array([[1,2], [3,4]]) 
print (np.linalg.det(a))
b = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (b)
print (np.linalg.det(b))
print (6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

-2.0000000000000004
[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0
-306


# numpy.linalg.det() 函数计算输入矩阵的行列式

In [14]:
# numpy.linalg.solve() 函数给出了矩阵形式的线性方程的解。
# numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵。
x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print (x)
print (y)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
# 线性方程：AX=B的解
a = np.array([[1,1,1],[0,2,5],[2,5,-1]]) 
 
print ('数组 a：')
print (a)
ainv = np.linalg.inv(a) 

print ('a 的逆：')
print (ainv)
 
print ('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print (b)
 
print ('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print (x)

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]


In [ ]:
# numpy.amin() 和 numpy.amax()
# numpy.amin() 用于计算数组中的元素沿指定轴的最小值。
# numpy.amax() 用于计算数组中的元素沿指定轴的最大值。
# numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。
# numpy.percentile()
# 百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 函数numpy.percentile()接受以下参数。
# numpy.median() 函数用于计算数组 a 中元素的中位数（中值）
# numpy.mean() 函数返回数组中元素的算术平均值。 如果提供了轴，则沿其计算。
# numpy.average() 函数根据在另一个数组中给出的各自的权重计算数组中元素的加权平均值。
